version: "3.9"
services:
    mvt-builder:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./input:/data/input:ro
            - ./output:/data/output
            - ./pipeline.sh:/data/pipeline.sh:ro
        working_dir: /data
        command: ["bash", "./pipeline.sh"]
